package:
  name: 'gemgis'
  version: '0.1.6'

source:
  git_rev: v0.1.6
  git_url: https://github.com/cgre-aachen/gemgis

requirements:
  host:
    - python
    - setuptools
  build:
    - python
  run:
    - python
    - geopandas
    - rasterio
    - pyvista

about:
  home: https://github.com/cgre-aachen/gemgis
  license: LGPL
  license_family: LGPL
  license_file: LICENSE
  summary: GemGIS is a Python-based, open-source spatial information processing library

extra:
  recipe-maintainers:
    - AlexanderJuesel
