# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: gemgis

on: [push, pull_request]
  
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8.5]

    steps:
      - uses: conda-incubator/setup-miniconda@v1.7.0
        with:
         python-version: ${{ matrix.python-version }}
         mamba-version: "*"
         channels: conda-forge, defaults
      - uses: actions/checkout@v2  
      - name: install and test packages
        shell: bash -l {0}
        run: |
          mamba install -y -q -c conda-forge rasterio geopandas pyvista
          mamba install -y -q -c conda-forge flake8 pytest
          pip install -r requirements.txt

          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        
          pytest
